container:
  image: archlinux:base-devel
  cpu: 4
  memory: 8G
  greedy: true
  use_in_memory_disk: true
task:
  docker_builder:
     build_script:
          - chmod +x ./build.sh
          - ./build.sh
     upload_script:
         - chmod +x ./upload.sh
         - ./upload.sh

