container:
  image: archlinux:base-devel
  cpu: 8
  memory: 8G
  greedy: true
  use_in_memory_disk: true
  kvm: true
task:
  build_script:
      - chmod +x ./build.sh
      - ./build.sh
  build_script_cache: 
      folder: /tmp/cirrus-ci-build/output/    
  upload_script:
      - chmod +x ./upload.sh
      - ./upload.sh

